### ISSUE TITLE
Consistent `internal server errors` for STAIRS when submitting summaries copy-pasted from source text

### ISSUE THREAD

**Issue by langdonholmes** [learlab/itell-api#41] opened 2024-03-21 15:55 UTC
Summary scoring seems to be working fine - STAIRS seems to be the issue. I get an internal server error instead of a STAIRS redirection. Prevents users from moving on to the next chapter. Potential high-priority, but probably won't be as big of an issue since we're disabling copy-pasting. 

![Image](https://github.com/learlab/itell-api/assets/57017670/ec7c9d12-b97d-4383-92d4-71f3691e3f9c)

**Comment by langdonholmes** [comment] 2024-03-21 15:58
@jchoi92k I am having trouble reproducing this. Can you provide additional details?

I tested a summary copy/pasted from the page. I thought this might have been caused by a containment score of 1.0, but the API seems to handle that case without issue, so I'm not sure what's going on.

**Comment by jchoi92k** [comment] 2024-03-21 19:26
Seems like I can't reproduce it either.. Which is weird since I was getting this error consistently when I copy pasted from the source text.
Unsure what changed.. closing issue!

**Closed by jchoi92k** 2024-03-21 19:26 UTC

**Comment by langdonholmes** [comment] 2024-03-21 22:28
Thanks, Joon! Let's keep an eye on this one.
